name: React

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      
    - name: Install Dependencies
      path: WebApp
      run: yarn
      
    - name: Build
      path: WebApp
      run: yarn build
      
    - name: Test
      path: WebApp
      run: yarn test --watchAll=false
